### PR TITLE
Google crash course on ML

### PR DESCRIPTION
**Pull request by ankitkul**
Issue #93:

- [x] add link in the Deep Learning section.
- [x] add link in the Other Guides section.

I have used my best judgement to decide the order within each section but please let me know if you think otherwise.

### CODE REVIEW

**Comment by ankitkul** [comment]
Issues :-(
> Links 
  1. [L100] 404 https://fivethirtyeight.blogs.nytimes.com/fivethirtyeights-2012-forecast/

This link is broken and I couldn't find a fully functional link in the wayback machine as well. If you want I can raise a separate issue for the above link.

**Comment by hangtwenty** [comment]
@ankitkul Thanks so much for trying to fix that pesky link, I'll take a look

**Comment by hangtwenty** [comment]
Alrighty if you rebase onto master the error should be out of your way.

**Comment by hangtwenty** [comment]
@ankitkul This is great, can you just rephrase:

> which covers building deep neural network.

To

> which covers building deep neural networks.

(adding `s`)

Also, maybe it should say,

>which covers building deep neural networks with TensorFlow.

Since TensorFlow has a lot of name recognition these days. 😄

**Pull request merged**
