### PR TITLE
Minor revision for better formality and readability

### PR DESCRIPTION
**Pull request by wla80**
This commit is a part of my school assignment for revising technical document on github. Please feel free to provide me your feedback and hope the author can approve my pull request.

Thanks

### CODE REVIEW

**Comment by hangtwenty** [comment]
@wla80 Don't worry about the broken links by the way, for this repository I will handle it.

**Comment by hangtwenty** [comment]
I like some of this revision! Some parts I want to change though, as I try to keep a certain style and tone in this guide. 

What about this?

 > When you work on a real Machine Learning problem, you should focus your efforts on your **domain knowledge** and **data** before optimizing your choice of algorithms. You should strive for [Do Simple Things](http://wiki.c2.com/?DoSimpleThings) until you _have_ to increase complexity. You should not rush into neural networks because you think they're cool. To improve your model, get more data  and use your knowledge of the problem to manipulate the data. You should only optimize the choice of alogrithms after you have gathered enough data, and you've processed it well.

**Comment by wla80** [comment]
Hello @hangtwenty , thanks for your feedback. If you wish to maintain your style and tone, this looks good to me. I just uploaded the fix. Thank you

**Comment by hangtwenty** [comment]
@wla80 Thank you for the follow up and sorry for the delay! Merging

**Pull request merged**
