### PR TITLE
Added cybersecurity awesome lists

### PR DESCRIPTION
**Pull request by ankitkul**
Changes:
- Bullet points on reference material related to cyber security. 
- Minor reformatting

The [fsecurity](http://fsecurify.com/machine-learning-and-cyber-security/) link seems to be temporarily unavailable but I haven't removed it yet.

### CODE REVIEW

**Comment by ankitkul** [comment]
@hangtwenty Do let me know if this is good or you would like me to change something.

**Comment by hangtwenty** [comment]
Hey sorry for the delay I missed the first notification. One nitpick, the second link in the list is actually 'fsecurify' with an F, not a T. (currently it says 'fsecurity')

**Comment by hangtwenty** [comment]
Thanks for changing to the bullet list format, makes sense now that there are a couple more resources.

**Comment by hangtwenty** [comment]
Good point that fsecurify is missing... Let's change that link to the archive.org URL. Do you mind? It's http://web.archive.org/web/20170606105129/http://fsecurify.com/machine-learning-and-cyber-security/

**Comment by ankitkul** [comment]
@hangtwenty Thanks for the feedback. My first commit on open source and github so looks like my slight nervousness made me the miss the details :) . I will replace the link with the archive.org and correct the T to F in "fsecurify".

**Comment by ankitkul** [comment]
@hangtwenty Just pushed the commits.

**Comment by hangtwenty** [comment]
This is great. Thank you!

**Comment by ankitkul** [comment]
@hangtwenty Thanks. Dive into machine learning is awesome :) Glad to be contributing my 2 cents.

**Pull request merged**
