### PR TITLE
Add link to examples of codes for kaggle competitions

### PR DESCRIPTION
**Pull request by apeeyush**
This will make it easy for people to get started with kaggle contests and machine learning in general as they will be able to see some practical examples.

### CODE REVIEW

**Comment by hangtwenty** [comment]
Hey @apeeyush, thanks for the pull request. I'm not sure about this change though. Competitions are time-sensitive, and you can already go to the Kaggle site (already linked in the guide), and easily see what Kaggle competitions are active.

https://www.kaggle.com/competitions

This is a clean view, not hard to navigate at all, and it's guaranteed to be up-to-date since it's straight from the source.

So I do not see why we would need to add a link to an unofficial summary, when the Kaggle site itself provides this information.

Thank you!

**Comment by apeeyush** [comment]
Hi @hangtwenty 

The repository's main purpose is to provide some practical examples of how to use sklearn, pandas etc. in Kaggle contests (and machine learning in general). For example, the [code](https://github.com/apeeyush/machine-learning/tree/master/bike-sharing-demand) for city bike sharing system which creates an ensemble of rf and gbm scores 0.36996 on leaderboard (top 2% on leaderboard). Also, these contests are knowledge contests (the basic once).

In any case, it's your call if you want to merge it or not! Just wanted to clarify the purpose of repo :)

**Comment by hangtwenty** [comment]
Apologies, @apeeyush , I did not see the important sentences in the README:

>  This folder contains code and data for the competition.

Since I didn't see that (got lost in paragraphs, as I was skimming) ... all I was seeing was a README with links to Kaggle. I didn't get what the point was!

Now I understand.

I've submitted https://github.com/apeeyush/machine-learning/pull/1. After you change something like that, making the links stand out more ... then I think this is a great contribution :)

I mention Kaggle in 2 different places in this guide, so I'll need to "refactor" a little bit after merging this pull request. But I'll do that as a follow-up step.

**Comment by hangtwenty** [comment]
Hey @apeeyush thanks for merging https://github.com/apeeyush/machine-learning/pull/1. I will merge this PR then do that "refactoring," tomorrow

**Comment by hangtwenty** [comment]
Fyi @apeeyush  I decided to consolidate the notes on Kaggle to the "Towards Expertise" section, if you're wondering where your contribution is now. Thanks again.

**Pull request merged**
