### PR TITLE
Revision of advice for Practicing Machine Learning

### PR DESCRIPTION
**Pull request by hangtwenty**
A coworker recommended adding a link to HackerRank. (#28) Since this was yet another "challenges" resource ... but a unique one (the challenges are smaller/ bite-size) ... seemed useful, but also imbalanced the "Towards Expertise" section towards challenges/competitions, a little too much.

So that made me want to revise further, and emphasize that the challenges/competition way offers practice -- but that it should always be paired with understanding ... and also that the "independent research" approach -- doing practice projects driven by your own interests -- is complementary.

Slipped in a link to Data is Plural, as I've been wanting to (#30)

### CODE REVIEW

**Comment by hangtwenty** [comment]
@jsvine BTW Happy I found a neat place to tuck in a link to Data Is Plural, here :beers:

**Comment by jsvine** [comment]
@hangtwenty Oooh, thanks :tada:

**Comment by hangtwenty** [comment]
@jsvine thanks!

**Comment by hangtwenty** [comment]
@jkontny Any feedback? Seems good to me (nothing too controversial) just want more eyes on some of my changes.

**Pull request merged**
