### PR TITLE
Encourage newcomers to use Python 3

### PR DESCRIPTION
**Pull request by rhiever**
Great tutorial here. My one request is to please encourage newcomers to use Python 3, not Python 2. It's 2015 -- it's well past time for us to move on to Python 3. I modified your introductory part a little bit to:

1) Encourage the readers to use Python 3

2) Use the Anaconda Python distribution

Anaconda will make their life so much easier. Let's not get newcomers trapped into using `pip` when there's better tools available. :-)

### CODE REVIEW

**Comment by hangtwenty** [comment]
Thanks :)

I'll address your two changes separately.

*Python 3.* I agree with you in principle, I really do. I only mentioned that I'm using Python 2.7.5 to say, this is what I've tested with (so if you have another version, Your Mileage May Vary). But in the name of "choosing your battles," I do want to keep this guide focused. Since I do agree that people should use Python 3, I'll find a way to incorporate that. One concern is that many (valuable, viable, good) resources are still using Python 2.7.x. Across the whole Python ecosystem. Some of those resources might be linked in this notebook. I haven't made a pass to ensure they're all Python 3 compatible. Most likely ...  I'll add some verbiage to say something like, "Python. Use latest if you can! Python 3 is the best option. Python 2.7.x should work as well (I've tested with Python 2.7)" hopefully more concise. Then also I will track down a solid blog post about Python 2.7 and Python 3, link a word or two in that sentence if anybody cares to click through and understand the issue intimately.

*pip and Anaconda.* pip is good. It is official: https://github.com/pypa/pip . I will never recommend against pip, as it is _the_ package manager for Python. Any concerns with pip should be taken up with the pip maintainers ;) to your point though, Anaconda _is_ great. This guide should DEFINITELY recommend it. Anaconda will be the preference for many users. So I'll need to revise carefully to make it clear that both are viable options. The reader will know pretty well which one they prefer.

So yeah I think both are really good points. I just want to tweak to make sure I don't turn away people from any "camp." (camp 1, what I'm in: plain old Python, uses pip, prefers Python 2.7.x because acutely aware that a lot of of enterprise Python AND open-source Python is still only 2.7.x compatible; camp 2, more progressive folks who evangelize Python 3 (more power to 'em!); camp 3, people who use Anaconda and prefer that to pip ... camps 2 & 3 might be the same people sometimes. We all have different backgrounds, want to welcome all 2-3 camps here)

**Comment by rhiever** [comment]
wrt to Python 2 compatibility -- what major Python data science tools are still only Python 2 compatible? I believed this for a very long time, but most of the major Python data science tools (that I use) have been updated to support Python 3.

wrt to pip -- pip is indeed great! I still use pip to install packages outside the Anaconda ecosystem. But Anaconda can be used to install all the most-used Python data science packages, and really helps avoid installation and compatibility headaches that sometimes arise with pip. As someone who has taught hundreds of newcomers to Python, I can tell you that installation is one of the biggest headaches for beginners, and the Anaconda Python distribution solves 99.9% of them. I wouldn't say get rid of mentions of pip entirely, but I would strongly recommend that you point newcomers to Anaconda first rather than it being an alternative to pip.

**Comment by hangtwenty** [comment]
@rhiever OK yeah, you're convincing me about pip. I still want to [learn a little more about how pip and Anaconda play together](http://stackoverflow.com/a/18640601/884640) but I'll "point newcomers to Anaconda first rather than it being an alternative to pip," as you've said.

Regarding Python 3 compatibility, I'll just have to trust you about data science being ahead of the curve. I still routinely use libraries at work that are not Python 3 compatible yet. So I'll recommend Python 3 ... probably still something like "Python. Use latest if you can! Python 3 is the best option. Python 2.7.x should work as well (I've tested with Python 2.7)" but try to cut some words out, have 1 word link to a good blog post for context if anyone's curious.

I'm grateful for this contribution and you taking the time to discuss it with me. I'm going to merge it now. Then adjust as a followup.

**Comment by rhiever** [comment]
Cheers! :+1:

On Wednesday, October 21, 2015, hangtwentyy <notifications@github.com>
wrote:

> @rhiever <https://github.com/rhiever> OK yeah, you're convincing me about
> pip. I still want to learn a little more about how pip and Anaconda play
> together <http://stackoverflow.com/a/18640601/884640> but I'll "point
> newcomers to Anaconda first rather than it being an alternative to pip," as
> you've said.
>
> Regarding Python 3 compatibility, I'll just have to trust you about data
> science being ahead of the curve. I still routinely use libraries at work
> that are not Python 3 compatible yet. So I'll recommend Python 3 ...
> probably still something like "Python. Use latest if you can! Python 3 is
> the best option. Python 2.7.x should work as well (I've tested with Python
> 2.7)" but try to cut some words out, have 1 word link to a good blog post
> for context if anyone's curious.
>
> I'm grateful for this contribution and you taking the time to discuss it
> with me. I'm going to merge it now. Then adjust as a followup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hangtwenty/dive-into-machine-learning/pull/4#issuecomment-150013786>
> .
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Pull request merged**
