### PR TITLE
Added andrew ng deeplearning.ai course

### PR DESCRIPTION
**Pull request by prajjwal1**
Andrew Ng's latest course on deep learning. Covers all the important topics with implementation of tensorflow .

### CODE REVIEW

**Comment by hangtwenty** [comment]
Thank you! I will definitely merge this. The Travis CI checks for link status codes, and it's hitting an issue right now **unrelated** to your PR. I will address that then merge your PR.

**Comment by prajjwal1** [comment]
Where is the issue lying ?

**Comment by hangtwenty** [comment]
>Where is the issue lying ?

Thanks for asking - just links that got broken. You didn't cause it, it's just a check that runs on every commit.

**Comment by hangtwenty** [comment]
Thanks again @prajjwal1 !

**Pull request merged**
